/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    gallery: Gallery;
    audio: Audio;
    videos: Video;
    media: Media;
    comments: Comment;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    audio: AudioSelect<false> | AudioSelect<true>;
    videos: VideosSelect<false> | VideosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    identity: Identity;
    contact: Contact;
  };
  globalsSelect: {
    identity: IdentitySelect<false> | IdentitySelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * यहाँ से नई रचना जोड़िए। सहेजने पर "Draft" रहती है — "Publish" दबाने पर ही साइट पर आती है।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * पते में यही आता है — /posts/kuch-paya-kuch-chhoot-gaya
   */
  slug: string;
  /**
   * सूची और कार्ड पर दिखने वाली दो-तीन पंक्तियाँ।
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: number | Category;
  /**
   * रचना के पन्ने पर सबसे ऊपर, पूरी चौड़ाई में दिखती है। बहुत चौड़ी तस्वीर चुनिए — कम से कम 1900px चौड़ी। इसके ऊपर शीर्षक छपता है, इसलिए साइट इसे गहरा कर देती है और ऊपर-नीचे से थोड़ी कट सकती है, तो ज़रूरी हिस्सा बीच में रखिए। खाली छोड़ेंगे तो साइट की अपनी बनी-बनाई तस्वीर लग जाएगी — कुछ टूटेगा नहीं।
   */
  bannerImage?: (number | null) | Media;
  /**
   * रचना के साथ लगी तस्वीर। वीडियो चलाने से पहले जो तस्वीर दिखती है, वह भी यही है (जब मंच अपनी तस्वीर न दे, जैसे Instagram)।
   */
  coverImage?: (number | null) | Media;
  /**
   * रचना का पाठ। रचना के बग़ल में सुनने का बटन दिखेगा।
   */
  audio?: (number | null) | Audio;
  /**
   * YouTube या Instagram reel का लिंक चिपकाइए — जैसा है वैसा ही। रचना के बग़ल में वीडियो दिखेगा।
   */
  videoUrl?: string | null;
  /**
   * हिन्दी में लिखिए — जैसे "1 अगस्त 2026"। जैसा लिखेंगे वैसा ही दिखेगा।
   */
  displayDate: string;
  /**
   * सूची का क्रम इसी से तय होता है। पाठकों को यह नहीं दिखती।
   */
  publishedAt: string;
  /**
   * बड़ा नंबर ऊपर दिखता है। सामान्यतः 0 ही रहने दीजिए।
   */
  order: number;
  views?: number | null;
  likes?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * जैसे: संस्मरण, कविता, मार्गदर्शन
   */
  name: string;
  /**
   * पते में यही आता है — /category/kavita
   */
  slug: string;
  /**
   * श्रेणी के पन्ने पर ऊपर दिखेगा।
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * स्क्रीन-रीडर इसे पढ़ते हैं और तस्वीर न खुलने पर यही दिखता है। एक छोटा वाक्य लिखिए।
   */
  alt: string;
  /**
   * तस्वीर के नीचे दिखने वाली पंक्ति। खाली छोड़ सकते हैं।
   */
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * रचना पढ़कर रिकॉर्ड की हुई फ़ाइल — mp3 या m4a। यहाँ जो चढ़ेगा वह गैलरी के "आलोक की आवाज़ें" खाने में भी दिखेगा, और रचना के साथ भी लगाया जा सकता है।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio".
 */
export interface Audio {
  id: number;
  /**
   * गैलरी में यही दिखेगा, और रचना के साथ लगाते समय पहचानने के काम आएगा — जैसे "कुछ पाया — पाठ"।
   */
  title: string;
  /**
   * बड़ा नंबर पहले दिखता है। सामान्यतः 0 ही रहने दीजिए।
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * गैलरी वाले पन्ने की तस्वीरें। यहाँ जो जोड़ेंगे सिर्फ़ वही साइट पर दिखेगा। नई फ़ाइल चढ़ाइए, या "पहले से चढ़ी हुई तस्वीर" में से चुन लीजिए। क्रम बदलना हो तो नीचे का नंबर बदलिए।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  /**
   * जो तस्वीर पहले से "तस्वीरें / Media" में है उसे यहाँ चुन लीजिए — दोबारा चढ़ाने की ज़रूरत नहीं। अगर आप ऊपर नई फ़ाइल चढ़ा रहे हैं तो इसे खाली छोड़ दीजिए। दोनों भरे हों तो ऊपर वाली फ़ाइल ही दिखेगी।
   */
  mediaImage?: (number | null) | Media;
  /**
   * तस्वीर के नीचे हाथ की लिखावट में दिखेगा — जैसे "अपनी गली में"।
   */
  caption: string;
  /**
   * स्क्रीन-रीडर इसे पढ़ते हैं और तस्वीर न खुलने पर यही दिखता है। पहले से चढ़ी हुई तस्वीर चुनी है तो खाली छोड़ सकते हैं — उसका अपना विवरण इस्तेमाल हो जाएगा।
   */
  alt?: string | null;
  /**
   * बड़ा नंबर पहले दिखता है। सामान्यतः 0 ही रहने दीजिए।
   */
  order: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * गैलरी के "चलचित्र" खाने में दिखने वाले वीडियो। YouTube या Instagram का लिंक चिपकाइए — फ़ाइल चढ़ाने की ज़रूरत नहीं।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos".
 */
export interface Video {
  id: number;
  /**
   * वीडियो के नीचे दिखेगा — जैसे "एक शाम, एक कविता"।
   */
  title: string;
  /**
   * YouTube या Instagram reel का लिंक, जैसा है वैसा ही चिपकाइए। tracking वाला हिस्सा साइट ख़ुद हटा देती है।
   */
  videoUrl: string;
  /**
   * बड़ा नंबर पहले दिखता है। सामान्यतः 0 ही रहने दीजिए।
   */
  order: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * नई टिप्पणियाँ "प्रतीक्षा में" रहती हैं। पढ़कर "स्वीकृत" कीजिए, तभी साइट पर दिखेंगी।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: number;
  post: number | Post;
  authorName: string;
  /**
   * साइट पर कभी नहीं दिखेगा — सिर्फ़ आपके लिए।
   */
  authorEmail?: string | null;
  body: string;
  status: 'pending' | 'approved' | 'spam';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'gallery';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'audio';
        value: number | Audio;
      } | null)
    | ({
        relationTo: 'videos';
        value: number | Video;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'comments';
        value: number | Comment;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  bannerImage?: T;
  coverImage?: T;
  audio?: T;
  videoUrl?: T;
  displayDate?: T;
  publishedAt?: T;
  order?: T;
  views?: T;
  likes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  mediaImage?: T;
  caption?: T;
  alt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio_select".
 */
export interface AudioSelect<T extends boolean = true> {
  title?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "videos_select".
 */
export interface VideosSelect<T extends boolean = true> {
  title?: T;
  videoUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  authorName?: T;
  authorEmail?: T;
  body?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * आपका परिचय — नाम, भूमिका, गोल तस्वीर, दो पंक्तियाँ अपने बारे में, और दस्तख़त। यह होम पन्ने पर और हर रचना के शीर्षक के नीचे दिखता है। Save करते ही साइट दोबारा बन जाती है।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity".
 */
export interface Identity {
  id: number;
  /**
   * होम पन्ने पर दो जगह, हर रचना के शीर्षक के नीचे गोल तस्वीर के साथ, और नीचे की पट्टी में copyright में भी — अगर वह खाना खाली छोड़ा हो।
   */
  byline: string;
  /**
   * नाम के ठीक नीचे, छोटे अक्षरों में — जैसे "कवि"। होम पन्ने पर और हर रचना के नीचे नाम के साथ दिखती है।
   */
  role?: string | null;
  /**
   * दो-तीन पंक्तियाँ — आप कहाँ के हैं, कब से लिखते हैं, और क्यों। ज़्यादा औपचारिक मत कीजिए।
   */
  bio?: string | null;
  /**
   * परिचय के नीचे हाथ की लिखावट वाला दस्तख़त। आमतौर पर सिर्फ़ पहला नाम — पूरा नाम यहाँ भरा तो पंक्ति टूट सकती है।
   */
  signature?: string | null;
  /**
   * होम पन्ने के पीछे पूरी चौड़ाई में दिखने वाली तस्वीर। चौड़ी (landscape) तस्वीर चुनिए — कम से कम 1600px चौड़ी। इसके ऊपर लिखावट आती है, इसलिए साइट इसे थोड़ा गहरा कर देती है। खाली छोड़ेंगे तो पतंगों वाली पुरानी तस्वीर ही रहेगी।
   */
  heroImage?: (number | null) | Media;
  /**
   * पोलरॉइड फ़्रेम में दिखने वाली तस्वीर। खड़ी (portrait) तस्वीर सबसे अच्छी लगती है — फ़्रेम 4:5 का है और बाक़ी हिस्सा अपने आप कट जाता है, इसलिए चेहरा बीच में रखिए। खाली छोड़ेंगे तो पुरानी तस्वीर ही रहेगी।
   */
  portraitImage?: (number | null) | Media;
  /**
   * हर रचना के शीर्षक के नीचे, नाम के साथ दिखने वाली छोटी गोल तस्वीर। सिर्फ़ चेहरे वाली, चौकोर (square) तस्वीर सबसे अच्छी लगती है — कम से कम 200px। खाली छोड़ेंगे तो ऊपर वाली "अपनी तस्वीर" ही गोल करके दिखा दी जाएगी।
   */
  avatarImage?: (number | null) | Media;
  /**
   * पोलरॉइड के नीचे हाथ से लिखी-सी पंक्ति।
   */
  portraitCaption?: string | null;
  /**
   * पुराने कैमरे जैसी नारंगी तारीख़, तस्वीर के कोने में। जैसा लिखेंगे वैसा ही छपेगा — यह असली तारीख़ नहीं है, सजावट है।
   */
  portraitDatestamp?: string | null;
  /**
   * नीचे की पट्टी में दिखता है।
   */
  handle?: string | null;
  /**
   * खाली छोड़िए — तब "© <पूरा नाम>" अपने आप बन जाता है और नाम बदलने पर साथ ही बदल जाता है। कुछ और लिखना हो तभी भरिए।
   */
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * संपर्क पन्ने पर जो दिखता है — शीर्षक, ठिकानों की पंक्तियाँ, और नीचे की पंक्ति। Save करते ही साइट दोबारा बन जाती है।
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  /**
   * पन्ने के ऊपर बड़े अक्षरों में। खाली छोड़ेंगे तो "संपर्क" ही रहेगा।
   */
  heading?: string | null;
  /**
   * शीर्षक के ठीक नीचे की छोटी पंक्ति।
   */
  subheading?: string | null;
  /**
   * जितने ठिकाने चाहें जोड़िए — ईमेल, Instagram, YouTube, Facebook, WhatsApp, कुछ भी। बाईं ओर से खींचकर क्रम बदल सकते हैं। सारी पंक्तियाँ हटा देंगे तो पन्ने पर सिर्फ़ शीर्षक बचेगा।
   */
  rows?:
    | {
        /**
         * ऊपर छोटे अक्षरों में — जैसे "ईमेल", "Instagram"।
         */
        label: string;
        /**
         * पाठक को यही पढ़ने को मिलता है — जैसे "@ambarkibaatein"। खाली छोड़ेंगे तो पता ही दिख जाएगा।
         */
        text?: string | null;
        /**
         * पूरा लिंक चिपकाइए — https://www.instagram.com/… । ईमेल हो तो सिर्फ़ पता लिखिए (alok@aajneeti.social), "mailto:" लगाने की ज़रूरत नहीं। फ़ोन के लिए tel:+91… चलेगा।
         */
        href: string;
        /**
         * खाली छोड़िए तो बटन नहीं आएगा। जैसे "Follow", "Subscribe"। ⚠️ बटन ख़ुद फ़ॉलो या subscribe नहीं करता — वह सिर्फ़ वहाँ ले जाता है जहाँ पाठक उनका अपना बटन दबाता है। कोई भी साइट दूसरी साइट की ओर से यह नहीं कर सकती।
         */
        buttonLabel?: string | null;
        /**
         * खाली छोड़ेंगे तो बटन ऊपर वाले पते पर ही ले जाएगा। YouTube के लिए लिंक के आख़िर में ?sub_confirmation=1 जोड़ने पर चैनल खुलते ही subscribe की डिबिया सामने आ जाती है।
         */
        buttonHref?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * डिब्बे के नीचे, हल्के रंग में। खाली छोड़ेंगे तो कुछ नहीं छपेगा।
   */
  note?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "identity_select".
 */
export interface IdentitySelect<T extends boolean = true> {
  byline?: T;
  role?: T;
  bio?: T;
  signature?: T;
  heroImage?: T;
  portraitImage?: T;
  avatarImage?: T;
  portraitCaption?: T;
  portraitDatestamp?: T;
  handle?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  rows?:
    | T
    | {
        label?: T;
        text?: T;
        href?: T;
        buttonLabel?: T;
        buttonHref?: T;
        id?: T;
      };
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}